podcast_title: "Rav Shamai Wahrman - Amud Yomi"
podcast_author: "Rav Shamai Wahrman"
podcast_description: "Amud Yomi shiurim by Rav Shamai Wahrman."
language: "en-us"
source_example_url: "https://www.yutorah.org/lectures/1178830/Amud-Yomi:-Makkos-2a"
episode_title_cleanup:
  remove_prefixes:
    - "Amud Yomi:"
archive_identifier_prefix: "rav-shamai-wahrman-amud-yomi"
